name: senior_surfers
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_tts: ^4.2.2
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4
  flutter_chess_board: ^1.0.1
  syncfusion_flutter_pdfviewer: ^29.1.39
  path_provider: ^2.0.10
  device_frame: ^1.1.0
  font_awesome_flutter: ^10.5.0
  fluttertoast: ^8.2.2
  flutter_password_strength: ^0.1.0
  app_links: ^3.0.0  # Use the latest compatible version
  provider: ^6.1.5
  shared_preferences: ^2.5.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/seniorsurfersLogoNoName.png
    - assets/images/tutorial.png
    - assets/images/practice.png
    - assets/images/tech_glossary.png
    - assets/images/notification.png
    - assets/images/games.png
    - assets/images/community_forum.png
    - assets/images/bgdesign_welcome.png
    - assets/images/facebooklogo.png
    - assets/images/googlelogo.png
    - assets/images/games/damma.png
    - assets/images/games/solitaire.png
    - assets/images/games/chess.png
    - assets/images/elder.png
    - assets/images/achievements.png
    - assets/images/practice/viber.png 
    - assets/images/practice/whatsapp.png 
    - assets/images/practice/cliqq.png 
    - assets/images/practice/gmeet.png 
    - assets/images/practice/zoom.png 
    - assets/images/practice/gmail.png
    - assets/pdf/tutorial1.png
    - assets/pdf/pdfbg.png
    - assets/images/gmeetdesign.png
    - assets/images/elderpfp.png
    - assets/pdf/tutorial1.pdf

  fonts:
    - family: Caros
      fonts:
        - asset: assets/font/Caros-Regular.otf
